### ISSUE TITLE
just wanted to say thank you!

### ISSUE THREAD

**Issue by cjp256** [mxmeinhold/pylint-fixme-info#1]
This is exactly how I want my TODOs handled :D :partying_face: 

TODOs shouldn't be discouraged, they should be tasks that are regularly in your face until you address it! :stuck_out_tongue_winking_eye:

**Comment by mxmeinhold** [comment]
Glad this has been helpful! I had the same thought working on a personal project and was surprised there wasn't any configuration for this.

Just curious, how'd you find this? I published this 4 days ago and did not expect anyone other than me to be finding it anytime soon!

**Comment by cjp256** [comment]
Pretty sure I just googled "pylint fixme" and/or "pylint fixme info rather than error" and the PyPI link is near the top.  They must highly rank published pypi projects (or I just got lucky) :D

**Comment by mxmeinhold** [comment]
That's awesome! I'm gonna close this issue so it drops off my dashboard, but thank you for submitting this! It's really nice to see things I've made in use beyond my immediate circles.
